"""created tables

Revision ID: 678488e49a63
Revises: 7dfffa824e98
Create Date: 2023-09-06 21:54:04.236014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '678488e49a63'
down_revision = '7dfffa824e98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('cus_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('cus_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer')
    # ### end Alembic commands ###
